### ISSUE TITLE
Release on opam

### ISSUE THREAD

**Issue by tmattio** [patricoferris/hilite#1]
Hi 🙂 

As I'm working on upstreaming the dependencies we use for https://github.com/ocaml/ocaml.org, I was wondering if we could release hilite on opam?

It's been in use for some time now to generate the content of https://v3.ocaml.org/, and looks stable. What do you think?

Let me know if I can help with anything!

**Comment by patricoferris** [comment]
Sorry for the delay @tmattio !!

Before cutting a release, are there any other syntaxes you want? I've been copying them from vscode for the moment ?

**Comment by tmattio** [comment]
No worries! I also realized there were changes made on v3, so I opened #2 to upstream these.

I can't think of another syntax right now. In the longer term, it could be useful to have general syntaxes like sh, html, etc. but what we have in v3 works great at the moment!

**Comment by patricoferris** [comment]
Agreed!

Managed a nice round PR number too! https://github.com/ocaml/opam-repository/pull/21200

**Comment by patricoferris** [comment]
It has been released :)))

**Comment by tmattio** [comment]
Thanks a lot @patricoferris 🎉
