### ISSUE TITLE
Render highlighted source code as Tyxml 

### ISSUE THREAD

**Issue by Tim-ats-d** [patricoferris/hilite#14]
Maybe in another package since it means adding a dependency

**Comment by patricoferris** [comment]
Hey @Tim-ats-d -- thanks for the issue, given the recent change to `Cmarkit` I think what would be needed here is a `Cmarkit_tyxml` renderer which could be used to take a `Cmarkit.Doc.t` to Tyxml. In which case, not sure there's much the Hilite package can do. Please do disagree if I've interpreted this incorrectly.
