### ISSUE TITLE
Cmarkit branch not rederering content

### ISSUE THREAD

**Issue by oyenuga17** [patricoferris/hilite#15]
Hi @patricoferris thank you for this amazing tool 😊 
I tried to pin and use the cmarkit branch of hilite [here](https://github.com/ocaml/ocaml.org/pull/1642) on [ocaml.org](https://github.com/ocaml/ocaml.org). but it doesn't render the contents passed through it. Do you have any pointers on how I can use this?

Here is how I try to use it: 
https://github.com/ocaml/ocaml.org/blob/c7fb5b0de75f37d325f9c8a4846dc8c6c81e65d1/tool/ood-gen/lib/changelog.ml#L25-L46

Here is the behavior I'm experiencing:

**Before**
<img width="1300" alt="Screenshot 2023-10-18 at 17 10 17" src="https://github.com/patricoferris/hilite/assets/64274826/87e86a0f-4c55-437f-b016-36eead869966">

**After**
<img width="1381" alt="Screenshot 2023-10-18 at 17 12 02" src="https://github.com/patricoferris/hilite/assets/64274826/c11fd75f-4ee7-468a-b5e1-d3fb1abe3f9c">

**Comment by patricoferris** [comment]
Thanks for the issue @oyenuga17 -- think we hammered out all the issues on ocaml.org and will merge #11 shortly and cut a release. Thank you for the help and groundwork here, it was incredibly useful and the only reason this change is being upstreamed and published.
